### ISSUE TITLE
Issue with loading the component - Channel 12 URL

### ISSUE THREAD

**Issue by GuyKh** [yohaybn/HomeAssistant-Israeli_TV#1]
```
2024-08-11 10:01:59.456 ERROR (MainThread) [homeassistant.setup] Error during setup of component israeli_tv
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/israeli_tv/__init__.py", line 153, in async_setup
    await sync_stations()
  File "/config/custom_components/israeli_tv/__init__.py", line 119, in sync_stations
    url=await get_channel_12_url(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/israeli_tv/__init__.py", line 39, in get_channel_12_url
    _LOGGER.debug("async_setup json: %s", json.loads(src)["tickets"])
                                          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

When manually using `POST https://mass.mako.co.il/ClicksStatistics/entitlementsServicesV2.jsp?et=gt&lp=/hls/live/512033/CH2LIVE_HIGH/index.m3u8&rv=AKAMAI` it returns the m3u successfully

**Comment by yohaybn** [comment]
I merged your code.
Thank you!
